export const COUNTRIES = {
  US: { name: "United States", flag: "🇺🇸" },
  CA: { name: "Canada", flag: "🇨🇦" },
  GB: { name: "United Kingdom", flag: "🇬🇧" },
  DE: { name: "Germany", flag: "🇩🇪" },
  FR: { name: "France", flag: "🇫🇷" },
  JP: { name: "Japan", flag: "🇯🇵" },
  AU: { name: "Australia", flag: "🇦🇺" },
  BR: { name: "Brazil", flag: "🇧🇷" },
  IN: { name: "India", flag: "🇮🇳" },
  CN: { name: "China", flag: "🇨🇳" },
  MX: { name: "Mexico", flag: "🇲🇽" },
  ES: { name: "Spain", flag: "🇪🇸" },
  IT: { name: "Italy", flag: "🇮🇹" },
  NL: { name: "Netherlands", flag: "🇳🇱" },
  SE: { name: "Sweden", flag: "🇸🇪" },
  NO: { name: "Norway", flag: "🇳🇴" },
  DK: { name: "Denmark", flag: "🇩🇰" },
  FI: { name: "Finland", flag: "🇫🇮" },
  CH: { name: "Switzerland", flag: "🇨🇭" },
  AT: { name: "Austria", flag: "🇦🇹" },
  BE: { name: "Belgium", flag: "🇧🇪" },
  PL: { name: "Poland", flag: "🇵🇱" },
  RU: { name: "Russia", flag: "🇷🇺" },
  KR: { name: "South Korea", flag: "🇰🇷" },
  SG: { name: "Singapore", flag: "🇸🇬" },
  HK: { name: "Hong Kong", flag: "🇭🇰" },
  TW: { name: "Taiwan", flag: "🇹🇼" },
  TH: { name: "Thailand", flag: "🇹🇭" },
  VN: { name: "Vietnam", flag: "🇻🇳" },
  ID: { name: "Indonesia", flag: "🇮🇩" },
  MY: { name: "Malaysia", flag: "🇲🇾" },
  PH: { name: "Philippines", flag: "🇵🇭" },
  ZA: { name: "South Africa", flag: "🇿🇦" },
  EG: { name: "Egypt", flag: "🇪🇬" },
  NG: { name: "Nigeria", flag: "🇳🇬" },
  AR: { name: "Argentina", flag: "🇦🇷" },
  CL: { name: "Chile", flag: "🇨🇱" },
  CO: { name: "Colombia", flag: "🇨🇴" },
  PE: { name: "Peru", flag: "🇵🇪" },
  VE: { name: "Venezuela", flag: "🇻🇪" },
  TR: { name: "Turkey", flag: "🇹🇷" },
  SA: { name: "Saudi Arabia", flag: "🇸🇦" },
  AE: { name: "United Arab Emirates", flag: "🇦🇪" },
  IL: { name: "Israel", flag: "🇮🇱" },
  IR: { name: "Iran", flag: "🇮🇷" },
  IQ: { name: "Iraq", flag: "🇮🇶" },
  PK: { name: "Pakistan", flag: "🇵🇰" },
  BD: { name: "Bangladesh", flag: "🇧🇩" },
  LK: { name: "Sri Lanka", flag: "🇱🇰" },
  NP: { name: "Nepal", flag: "🇳🇵" },
  MM: { name: "Myanmar", flag: "🇲🇲" },
  KH: { name: "Cambodia", flag: "🇰🇭" },
  LA: { name: "Laos", flag: "🇱🇦" },
  MN: { name: "Mongolia", flag: "🇲🇳" },
  KZ: { name: "Kazakhstan", flag: "🇰🇿" },
  UZ: { name: "Uzbekistan", flag: "🇺🇿" },
  AF: { name: "Afghanistan", flag: "🇦🇫" },
  UA: { name: "Ukraine", flag: "🇺🇦" },
  BY: { name: "Belarus", flag: "🇧🇾" },
  LT: { name: "Lithuania", flag: "🇱🇹" },
  LV: { name: "Latvia", flag: "🇱🇻" },
  EE: { name: "Estonia", flag: "🇪🇪" },
  CZ: { name: "Czech Republic", flag: "🇨🇿" },
  SK: { name: "Slovakia", flag: "🇸🇰" },
  HU: { name: "Hungary", flag: "🇭🇺" },
  RO: { name: "Romania", flag: "🇷🇴" },
  BG: { name: "Bulgaria", flag: "🇧🇬" },
  HR: { name: "Croatia", flag: "🇭🇷" },
  SI: { name: "Slovenia", flag: "🇸🇮" },
  RS: { name: "Serbia", flag: "🇷🇸" },
  BA: { name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  ME: { name: "Montenegro", flag: "🇲🇪" },
  MK: { name: "North Macedonia", flag: "🇲🇰" },
  AL: { name: "Albania", flag: "🇦🇱" },
  GR: { name: "Greece", flag: "🇬🇷" },
  CY: { name: "Cyprus", flag: "🇨🇾" },
  MT: { name: "Malta", flag: "🇲🇹" },
  PT: { name: "Portugal", flag: "🇵🇹" },
  IE: { name: "Ireland", flag: "🇮🇪" },
  IS: { name: "Iceland", flag: "🇮🇸" },
  LU: { name: "Luxembourg", flag: "🇱🇺" },
  LI: { name: "Liechtenstein", flag: "🇱🇮" },
  MC: { name: "Monaco", flag: "🇲🇨" },
  AD: { name: "Andorra", flag: "🇦🇩" },
  SM: { name: "San Marino", flag: "🇸🇲" },
  VA: { name: "Vatican City", flag: "🇻🇦" },
} as const;

export default COUNTRIES;
